=== TimothyPecceu/XMLStudie/src/oefening_XML_Schema.xsd
<!-- 
Er kunnen ook geen boeken aanwezig zijn in de lijst. Elk boek heeft minimaal 1
curriculum en 1 onderwerp. De beroepencode bestaat steeds uit 6 cijfers.
-->
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    <xs:simpleType name="beroepenCodeType">
        <xs:restriction base="xs:nonNegativeInteger">
            <xs:pattern value="/d{6}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="ISBNnrType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{9}[a-zA-Z0-9]"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="onderwerpType">
        <xs:simpleContent>
            <xs:extension base="xs:string"/>
        </xs:simpleContent>
        <xs:attribute name="nr" type="xs:nonNegativeInteger"/>
    </xs:complexType>
 
    <xs:complexType name="curriculumType">
        <xs:sequence>
            <xs:element name="Naam" type="xs:string"/>
            <xs:element name="Beroepencode" type="beroepenCodeType"/>
        </xs:sequence>
        <xs:attribute name="nr" type="xs:nonNegativeInteger"/>
    </xs:complexType>
    
    <xs:complexType name="curriculumsType" mixed="true">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="Curriculum" type="curriculumType"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="onderwerpenType" mixed="true">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="Onderwerp" type="onderwerpType"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="boekType">
        <xs:sequence>
            <xs:element name="Titel" type="xs:string" />
            <xs:element name="Schrijver" type="xs:string"/>.
            <xs:element name="Uitgever" type="xs:string"/>
            <xs:element name="Curriculums" type="curriculumsType"/>
            <xs:element name="Onderwerpen" type="OnderwerpenType"/> 
        </xs:sequence>
        <xs:attribute name="boeknr" type="xs:nonNegativeInteger"/>
        <xs:attribute name="isbn" type="ISBNnrType"/>
    </xs:complexType>
    
    <xs:complexType name="boekenType">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="Boek" type="boekType"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:element name="Boeken" type="boekenType"/>
</xs:schema>

=== TimothyPecceu/XMLStudie/hans.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<ns1:Boeken
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ns1='http://www.vdab.be/XML_IMPORT'
    xsi:schemaLocation='http://www.vdab.be/XML_IMPORT src/oefening_XML_Schema.xsd'>
    <ns1:Boek boeknr="" isbn="">
        <ns1:Titel></ns1:Titel>
        <ns1:Schrijver></ns1:Schrijver>
        <ns1:Uitgever></ns1:Uitgever>
        <ns1:Curriculums>
            <ns1:Curriculum nr="">
                <ns1:Naam></ns1:Naam>
                <ns1:Beroepencode></ns1:Beroepencode>
            </ns1:Curriculum>
        </ns1:Curriculums>
        <ns1:Onderwerpen></ns1:Onderwerpen>
    </ns1:Boek>

</ns1:Boeken>
