=== TimothyPecceu/XMLStudie/src/reizen.xsd
<?xml version="1.0"?>


<xs:schema version="1.0"
           xmlns = "http://www.vdab.be/XML_IMPORT"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           targetNamespace="http://www.vdab.be/XML_IMPORT">

    <xs:simpleType name="valutaType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="EUR"/>
            <xs:enumeration value="USD"/>
            <xs:enumeration value="GBP"/>
            <xs:enumeration value="JPY"/>
            <xs:enumeration value="ZAR"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="beeldType">
        <xs:attribute name="source" type="xs:string" use="required"/>
        <xs:attribute name="hoogte" type="xs:nonNegativeInteger" use="required"/>
        <xs:attribute name="breedte" type="xs:nonNegativeInteger" use="required"/>
        <xs:attribute name="alt" type="xs:string" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="dagType">
        <xs:sequence>
            <xs:element name="titel" type="xs:string"/>
            <xs:element name="beschrijving" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="dagnr" type="xs:nonNegativeInteger" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="programmaType">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="dag" type="dagType"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="datumsType">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="datum" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="adressenType">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="webadres" type="xs:anyURI"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="prijsType">
        <xs:sequence>
            <xs:element name="bedrag" type="xs:nonNegativeInteger"/>
            <xs:element name="vluchtInbegrepen" type="xs:boolean"/>
            <xs:element name="Begeleid" type="xs:boolean"/>
        </xs:sequence>
        <xs:attribute name="valutaEenheid" type="valutaType"/>
    </xs:complexType>
    
    <xs:complexType name="reisType" mixed="true">
        <xs:sequence>
            <xs:element name="reistitel" type="xs:string"/>
            <xs:element name="beschrijving" type="xs:string"/>
            <xs:element name="tijdsduur" type="xs:string"/>
            <xs:element name="prijs" type="prijsType"/>
            <xs:element name="opmerkingen" type="xs:string" minOccurs="0"/>
            <xs:element name="dagprogramma" type="programmaType"/>
            <xs:element name="vertrekdata" type="datumsType" minOccurs="0"/>
            <xs:element name="webadressen" type="adressenType" minOccurs="0"/>
            <xs:element name="beeld" type="beeldType"/>
        </xs:sequence>
        <xs:attribute name="boekingsnr" type="xs:nonNegativeInteger"/>
    </xs:complexType>
    
    <xs:complexType name="reizenType">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="reis" type="reisType"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:element name="reizen" type="reizenType">
        <xs:unique name="reisKey">
            <xs:selector xpath=".//reis"/>
            <xs:field xpath="@boekingsnr"/>
        </xs:unique>
    </xs:element>
</xs:schema>

=== TimothyPecceu/XMLStudie/src/reizen.xml
<?xml version="1.0" encoding="UTF-8"?>

<reizen xmlns="http://www.vdab.be/XML_IMPORT"
       xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
        xsi:schemaLocation="http://www.vdab.be/XML_IMPORT reizen.xsd">
    
    <reis boekingsnr="624">
        <reistitel>Madagascar Adventure</reistitel>
        <beschrijving>
            Madagaskar is een land dat tot de verbeelding van vele reizigers spreekt. 
            Wonderlijk genoeg wordt het slechts door weinig mensen bezocht. 
            En dat terwijl natuurliefhebbers hier hun hart kunnen ophalen aan unieke, grotendeels inheemse flora en fauna. 
            Een fascinerende wereld van kameleons, lemuren, vogels en stekelwouden ontvouwt zich hier voor je. 
            Daarnaast bezit het eiland een aantrekkelijke mengeling van bevolkingsgroepen, ontstaan uit Aziatische en Afrikaanse voorouders.
        </beschrijving>
        <tijdsduur>10 dagen</tijdsduur>
        <prijs valutaEenheid="EUR">
            <bedrag>1646</bedrag>
            <vluchtInbegrepen>true</vluchtInbegrepen>
            <Begeleid>true</Begeleid>
        </prijs>
        <opmerkingen>
            Het dagprogramma wijkt iets af van wat in de brochure vermeld staat. 
            We verblijven op dag 7 en 8 namelijk niet in Fianarantsoa, maar in een prachtig natuurgebied ten zuiden hiervan.
            Er wordt ook aangeraden voldoende regenkledij mee te nemen.
        </opmerkingen>
        <dagprogramma>
            <dag dagnr="1">
                <titel>Vertrek, aankomst Antananarivo</titel>
                <beschrijving>
                    In de ochtend vliegen we via Parijs naar Antananarivo. 
                    Na aankomst op het vliegveld Ivato wordt je opgewacht door de reisbegeleider die je naar een hotel in de stad brengt.
                </beschrijving>
            </dag>
            <dag dagnr="2">
                <titel>Antananarivo  Antsirabe</titel>
                <beschrijving>
                    We stappen 's morgens meteen op de bus die ons naar over het centrale hoogland (het zogenaamde haut-plateau) naar Antsirabe brengt, de stad van de halfedelstenen. 
                    Reizend langs enorme erosiegaten, lavaka geheten, maken we bij Ambatolampy een korte wandeling langs rijstvelden en Merina huizen. 
                    De mooie koloniale stad Antsirabe was vroeger een luxe kuuroord met warme baden; we overnachten hier in een goed hotel met eigen wc en douche. 
                    Er is een leuke markt en overal zie je de pousse-pousse, een door de chinezen meegenomen riksja (looptaxi). 
                    's Avonds kun je in de stad uit eten gaan; net zoals in de meeste grotere plaatsen kun je hier erg lekker Chinees of Frans eten krijgen voor een 
                    laag bedrag: een simpele Madagassische maaltijd kost € 3, betere, vaak Frans geori�nteerde maaltijden kosten tussen de € 4.50 en € 9.
                </beschrijving>
            </dag>
            <dag dagnr="3">
                <titel>Antsirabe  Ambositra, vrije ochtend</titel>
                <beschrijving>
                    Na een Frans ontbijt heb je de ochtend vrij om de levendige en leuke markt van Antsirabe te verkennen. 
                    Je ontkomt er vrijwel niet aan om je net als de Madagassiër een stukje met de pousse-pousse te laten vervoeren. 
                    Op de markt zijn de mensen meestal erg nieuwsgierig en knopen graag een praatje met je aan. 
                    In het centrum tref je de levensmiddelen markt, waar de Indonesisch uitziende marktvrouwen je onder grote hilariteit de diverse pepersoorten willen laten proeven. 
                    Iets uit het centrum bevindt zich de markt voor stoffen, fietsonderdelen en nog veel meer, met voor de deur de grote parkeerplaats van de pousse-pousse's. 
                    De vaak tientallen chauffeurs doen hun uiterste best om de ritten te bemachtigen. 's Middags vertrekken we richting Ambositra. 
                    De weg voert langs prachtige, tegen de helling aangelegde rijstterrassen en door mimosa en eucalyptusbossen. 
                    Via een stevige klim over een droge berghelling komen we aan in Ambositra, de hoofdstad van de kunstnijverheid en het houtsnijwerk. 
                    Het rustige provinciestadje wordt gekenmerkt door mooie huizen en zeer vriendelijke mensen.
                </beschrijving>
            </dag>
            <dag dagnr="4">
                <titel>Ambositra, vrije dag</titel>
                <beschrijving>
                    Vandaag kun je een buitengewoon fraaie wandeling door de rijstvelden rondom Ambositra maken. 
                    Je komt dan uit bij het paleis van de Betsileokoningen dat door de Zafimanirystam met traditioneel houtsnijwerk is versierd. 
                    De sawaïs en de Aziatische gelaatstrekken en kleding van de bevolking doen je even in Azië wanen, maar de rode Afrikaanse aarde doen je snel weer beseffen in welk continent je eigenlijk bent. 
                    Via een klein dorpje waar rozenhout wordt bewerkt komen we uiteindelijk weer in de stad aan. 
                    Je kunt daar nog door de straten met hun karakteristieke huizen dwalen of in de winkeltjes een aardige collectie houtsnijwerk uit de regio bekijken. 
                    Ook een bezoek aan het klooster met zijn houtsnijwerkplaats is een aanrader.
                </beschrijving>
            </dag>
            <dag dagnr="5">
                <titel>Ankaranareservaat</titel>
                <beschrijving>
                    Deze dag bezoek je het Ankarana Reserve Special, ook wel bekend onder de naam Arote de Tsingy. 
                    Dit reservaat bestaat uit droogte bossen en lijmsteenformaties. 
                    Deze vlijmscherpe lijmsteenformaties worden Tsingy genoemd en zijn duizenden jaren geleden door watererosie gevormd. 
                    Deze grillige rotsen verbergen verschillende grotten met duizenden vleermuizen en  hoe vreemd het ook mag klinken krokodillen. 
                    Ook komen er meerdere soorten lemuren voor; ook de vogel en reptielen wereld is zeer gevarieerd in dit gebied. 
                    Veel natuurdocumentaires over Madagaskar zijn hier opgenomen. Deze dag zul je verschillende wandelingen maken om dit boeiende gebied te verkennen. 
                    De wandelingen zijn voor iedereen met een normale conditie goed te doen.
                </beschrijving>
            </dag>
            <dag dagnr="6">
                <titel>Ankarana  Nosy Komba</titel>
                <beschrijving>
                    In de morgen vertrek je naar de kust. Je rijdt door een vruchtbaar gedeelte van het noorden. 
                    Cacao, koffie en Ylang Ylang (een bloem die de basis voor vele parfums vormt) plantages zullen aan ons voorbijtrekken. 
                    Aangekomen aan de kust kun je lunchen in een wel heel mooi hotel. 
                    Hierna stap je op een rapide, een snelle boot, voor de overtocht naar het idyllische en rustige eilandje Nosy Komba. 
                    We overnachten in tweepersoons huisjes.
                </beschrijving>
            </dag>
            <dag dagnr="7">
                <titel>Nosy Komba</titel>
                <beschrijving>
                    Dit eiland is in tegenstelling tot het nabij gelegen Nosy Be gelukkig nog niet door veel toeristen ontdekt. 
                    Wel heeft het paradijselijk witte stranden, mooie koraalriffen en een afwisselende tropische vegetatie. 
                    Hier heb je de tijd om in alle rust de opgedane indrukken van de reis op je in te laten werken. 
                    Je kunt hier mooie wandelingen maken in het achterland van dit eiland; dit eiland heeft ook weer zijn eigen lemuren, in dit geval zwarte lemuren. 
                    Doordat ze volgens een fady (taboe) van het eiland niet gegeten mogen worden komen ze in grote getalen voor. 
                    Net voor de kust liggen prachtige koraalriffen die uitnodigen om te gaan snorkelen.
                </beschrijving>
            </dag>
            <dag dagnr="8">
                <titel>vrije dag</titel>
                <beschrijving>
                    We ontdekken het eiland verder.
                </beschrijving>
            </dag>
            <dag dagnr="9">
                <titel>Nosy Komba  Nosy Be, vlucht naar Antananarivo , terugvlucht</titel>
                <beschrijving>
                    's Ochtends brengt de rapide je naar Nosy Be, waar je het vliegtuig neemt om terug te keren naar Antananarivo. 
                    Hier kun je de rest van de dag vrij besteden. 's Avonds check je in voor je terugvlucht, welke vlak na middernacht vertrekt.
                </beschrijving>
            </dag>
            <dag dagnr="10">
                <titel>Aankomst in België</titel>
                <beschrijving>
                    We komen terug aan in België
                </beschrijving>
            </dag>
        </dagprogramma>
        <vertrekdata>
            <datum>15/1/2004</datum>
            <datum>2/2/2004</datum>
            <datum>13/3/2004</datum>
        </vertrekdata>
        <webadressen>
            <webadres>http://www.madagascar-tourisme.com</webadres>
            <webadres>http://www.tourisme-madagascar.com</webadres>
        </webadressen>
        <beeld source="madagascar.jpg" hoogte="300" breedte="455" alt="Madagascar"/>
    </reis>
    
    <reis boekingsnr="505">
        <reistitel>Woestijnen in Namibië</reistitel>
        <beschrijving>
            Deze safari gaat naar de twee mooiste woestijnen ter wereld waar verrassend grote aantallen wilde dieren, vogels en fauna &amp; flora voorkomen. 
            Ervaar de charme van één van de mooie kustplaatsen van Namibië en de ruime keuze aan avontuurlijke aktiviteiten die daar aangeboden worden. 
            Liefhebbers van woestijnen mogen deze safari niet missen!
        </beschrijving>
        <tijdsduur>8 dagen</tijdsduur>
